[phases.setup]
nixPkgs = ["python3", "git", "git-lfs", "bash"]

[phases.install]
cmds = [
    "python3 -m venv --without-pip /opt/venv",
    "/opt/venv/bin/python -m ensurepip --upgrade",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[variables]
NIXPACKS_PATH = "/opt/venv/bin"

[phases.build]
cmds = [
    "chmod +x setup_model.sh",
    "bash setup_model.sh"
]

[start]
cmd = "python3 download_model.py && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
